"""Add relay_booth_id to Room

Revision ID: 006
Revises: 005
Create Date: 2026-06-05 23:11:38.195277

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "006"
down_revision: Union[str, Sequence[str], None] = "005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rooms") as batch_op:
        batch_op.add_column(sa.Column("relay_booth_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_rooms_relay_booth_id_booths", "booths", ["relay_booth_id"], ["id"], ondelete="SET NULL"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rooms") as batch_op:
        batch_op.drop_constraint("fk_rooms_relay_booth_id_booths", type_="foreignkey")
        batch_op.drop_column("relay_booth_id")
    # ### end Alembic commands ###
