"""Add transcription config

Revision ID: 007
Revises: 006
Create Date: 2026-06-07 14:19:36.140046

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "007"
down_revision: Union[str, Sequence[str], None] = "006"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("booths", sa.Column("transcription_enabled", sa.Boolean(), server_default="0", nullable=False))
    op.add_column(
        "booths",
        sa.Column("transcription_model", sa.String(length=20), server_default=sa.text("'tiny'"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("booths", "transcription_model")
    op.drop_column("booths", "transcription_enabled")
    # ### end Alembic commands ###
