"""add floor transcription

Revision ID: 009
Revises: 008
Create Date: 2026-06-11 10:56:37.274976

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "009"
down_revision: Union[str, Sequence[str], None] = "008"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rooms", sa.Column("floor_transcription_enabled", sa.Boolean(), server_default="0", nullable=False))
    op.add_column(
        "rooms",
        sa.Column(
            "floor_transcription_provider", sa.String(length=20), server_default=sa.text("'local'"), nullable=False
        ),
    )
    op.add_column(
        "rooms",
        sa.Column("floor_transcription_model", sa.String(length=40), server_default=sa.text("'tiny'"), nullable=False),
    )
    op.add_column("rooms", sa.Column("floor_language_code", sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rooms", "floor_language_code")
    op.drop_column("rooms", "floor_transcription_model")
    op.drop_column("rooms", "floor_transcription_provider")
    op.drop_column("rooms", "floor_transcription_enabled")
    # ### end Alembic commands ###
