"""Add translation models

Revision ID: 011
Revises: 010
Create Date: 2026-06-11 19:44:53.483497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '011'
down_revision: Union[str, Sequence[str], None] = '010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_translation_languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=20), nullable=False),
    sa.Column('language_name', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_translation_room_language', 'room_translation_languages', ['room_id', 'language_code'], unique=True)
    op.create_table('transcript_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['transcript_segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_translation_segment_language', 'transcript_translations', ['segment_id', 'language_code'], unique=True)
    op.add_column('events', sa.Column('translation_openai_api_key', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('openrouter_api_key', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('gemini_api_key', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('anthropic_api_key', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('groq_api_key', sa.Text(), nullable=True))
    op.add_column('rooms', sa.Column('floor_translation_enabled', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('rooms', sa.Column('floor_translation_provider', sa.String(length=50), nullable=True))
    op.add_column('rooms', sa.Column('floor_translation_model', sa.String(length=100), nullable=True))
    op.add_column('rooms', sa.Column('floor_source_language_code', sa.String(length=20), server_default=sa.text("'en'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'floor_source_language_code')
    op.drop_column('rooms', 'floor_translation_model')
    op.drop_column('rooms', 'floor_translation_provider')
    op.drop_column('rooms', 'floor_translation_enabled')
    op.drop_column('events', 'groq_api_key')
    op.drop_column('events', 'anthropic_api_key')
    op.drop_column('events', 'gemini_api_key')
    op.drop_column('events', 'openrouter_api_key')
    op.drop_column('events', 'translation_openai_api_key')
    op.drop_index('ix_translation_segment_language', table_name='transcript_translations')
    op.drop_table('transcript_translations')
    op.drop_index('ix_translation_room_language', table_name='room_translation_languages')
    op.drop_table('room_translation_languages')
    # ### end Alembic commands ###
