"""add_booth_translation_settings

Revision ID: 012
Revises: 011
Create Date: 2026-06-12 05:45:20.522418

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "012"
down_revision: Union[str, Sequence[str], None] = "011"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "booth_translation_languages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("booth_id", sa.Integer(), nullable=False),
        sa.Column("language_code", sa.String(length=20), nullable=False),
        sa.Column("language_name", sa.String(length=100), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(["booth_id"], ["booths.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_translation_booth_language", "booth_translation_languages", ["booth_id", "language_code"], unique=True
    )
    op.add_column("booths", sa.Column("translation_enabled", sa.Boolean(), server_default="0", nullable=False))
    op.add_column("booths", sa.Column("translation_provider", sa.String(length=50), nullable=True))
    op.add_column("booths", sa.Column("translation_model", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("booths", "translation_model")
    op.drop_column("booths", "translation_provider")
    op.drop_column("booths", "translation_enabled")
    op.drop_index("ix_translation_booth_language", table_name="booth_translation_languages")
    op.drop_table("booth_translation_languages")
    # ### end Alembic commands ###
