"""add broadcast_unlocked to booths

Revision ID: 013
Revises: 012
Create Date: 2026-06-14 07:31:49.773092

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "013"
down_revision: Union[str, Sequence[str], None] = "012"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("booth_memberships", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=False)

    with op.batch_alter_table("booths", schema=None) as batch_op:
        batch_op.add_column(sa.Column("broadcast_unlocked", sa.Boolean(), server_default="0", nullable=False))

    with op.batch_alter_table("event_memberships", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=False)

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=True)

    with op.batch_alter_table("event_memberships", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=True)

    with op.batch_alter_table("booths", schema=None) as batch_op:
        batch_op.drop_column("broadcast_unlocked")

    with op.batch_alter_table("booth_memberships", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=True)
    # ### end Alembic commands ###
