"""rbac_refactor

Revision ID: 014
Revises: 013
Create Date: 2026-06-14 09:21:20.086987

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "014"
down_revision: Union[str, Sequence[str], None] = "013"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "room_memberships",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_membership_user_room", "room_memberships", ["user_id", "room_id"], unique=True)
    op.add_column("events", sa.Column("listener_join_code", sa.String(length=64), nullable=True))

    # 1. Rename event_admin -> event_owner
    op.execute("UPDATE event_memberships SET role = 'event_owner' WHERE role = 'event_admin'")
    op.execute("UPDATE booth_memberships SET role = 'event_owner' WHERE role = 'event_admin'")

    # 2. Migrate coordinator to room_coordinator
    op.execute("""
        INSERT INTO room_memberships (user_id, room_id, role, created_at)
        SELECT DISTINCT bm.user_id, b.room_id, 'room_coordinator', bm.created_at
        FROM booth_memberships bm
        JOIN booths b ON bm.booth_id = b.id
        WHERE bm.role = 'coordinator'
    """)
    op.execute("DELETE FROM booth_memberships WHERE role = 'coordinator'")

    op.execute("""
        INSERT INTO room_memberships (user_id, room_id, role, created_at)
        SELECT DISTINCT em.user_id, r.id, 'room_coordinator', em.created_at
        FROM event_memberships em
        JOIN rooms r ON em.event_id = r.event_id
        WHERE em.role = 'coordinator'
    """)
    op.execute("DELETE FROM event_memberships WHERE role = 'coordinator'")

    # 3. Remove listeners from DB (they now use join codes)
    op.execute("DELETE FROM event_memberships WHERE role = 'listener'")
    op.execute("DELETE FROM booth_memberships WHERE role = 'listener'")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "listener_join_code")
    op.drop_index("ix_membership_user_room", table_name="room_memberships")
    op.drop_table("room_memberships")
    # ### end Alembic commands ###
