"""add_floor_tts_enabled

Revision ID: 015
Revises: 014
Create Date: 2026-06-18 12:19:44.239760

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "015"
down_revision: Union[str, Sequence[str], None] = "014"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rooms", sa.Column("floor_tts_enabled", sa.Boolean(), server_default="0", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rooms", "floor_tts_enabled")
    # ### end Alembic commands ###
