"""Add AuthToken and User.email_verified

Revision ID: 018
Revises: 017
Create Date: 2026-07-10 10:50:16.584854

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "018"
down_revision: Union[str, Sequence[str], None] = "017"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("jti", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_type", sa.String(length=20), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_auth_tokens_jti"), "auth_tokens", ["jti"], unique=True)
    op.add_column("users", sa.Column("email_verified", sa.Boolean(), server_default="0", nullable=False))
    op.alter_column("users", "password_hash", existing_type=sa.VARCHAR(length=200), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "password_hash", existing_type=sa.VARCHAR(length=200), nullable=False)
    op.drop_column("users", "email_verified")
    op.drop_index(op.f("ix_auth_tokens_jti"), table_name="auth_tokens")
    op.drop_table("auth_tokens")
    # ### end Alembic commands ###
