"""multi_room_architecture

Revision ID: 020
Revises: 019
Create Date: 2026-08-10 22:11:05.054369

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "020"
down_revision: Union[str, Sequence[str], None] = "019"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_booths")

    # Pre-migration safety check: Fail loudly if any booth has room_id IS NULL
    connection = op.get_bind()
    null_booths = connection.execute(sa.text("SELECT id FROM booths WHERE room_id IS NULL")).fetchall()
    if null_booths:
        raise RuntimeError(
            f"Migration failed: found {len(null_booths)} booths with NULL room_id. "
            "You must manually assign these booths to a room before applying this migration."
        )

    # ### commands auto generated by Alembic - please adjust! ###

    # Depending on DB dialect (SQLite vs Postgres), alter_column might need batch_alter_table
    with op.batch_alter_table("booths") as batch_op:
        batch_op.alter_column("room_id", existing_type=sa.Integer(), nullable=False)
        batch_op.drop_index(op.f("ix_booths_event_language"))
        batch_op.create_index("ix_booths_room_language", ["room_id", "language_code"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("booths") as batch_op:
        batch_op.drop_index("ix_booths_room_language")
        batch_op.create_index(op.f("ix_booths_event_language"), ["event_id", "language_code"], unique=1)
        batch_op.alter_column("room_id", existing_type=sa.Integer(), nullable=True)
    # ### end Alembic commands ###
