"""add tts_enabled

Revision ID: 025
Revises: 024
Create Date: 2026-09-08 21:46:15.773928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '025'
down_revision: Union[str, Sequence[str], None] = '024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booth_translation_languages', sa.Column('tts_enabled', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('room_translation_languages', sa.Column('tts_enabled', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_translation_languages', 'tts_enabled')
    op.drop_column('booth_translation_languages', 'tts_enabled')
    # ### end Alembic commands ###
